name: "ci"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  NODE_VERSION: "14.17.0"

jobs:
  ci_tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.7.1
          run_install: true

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Lint project
        run: pnpm lint
