name: "ci"

on:
  pull_request:
    branches:
      - cool

env: 
  MAIN_BRANCH: refs/heads/cool

jobs:
  ci:
    uses: mrsauravsahu/actions/.github/workflows/ci-vscode-extension.yml@feat/ci-vscode-extension
