name: "ci"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env: 
  MAIN_BRANCH: refs/heads/main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Calculate node version
        id: calculateNodeVersion
        run: |
          NODE_VERSION=`cat .nvmrc`
          echo "::set-output name=NodeVersion::$NODE_VERSION"
          echo "node version = v$NODE_VERSION"

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.calculateNodeVersion.outputs.NodeVersion }}

      - name: Install packages
        run: npm ci

      - name: Lint project
        run: npm run lint
      
      - name: Build VSIX package
        run: npm run build -- -o custom-profiles-for-vscode.v${{ steps.calculateVersion.outputs.AppVersion }}.vsix

      - name: Run E2E tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test:e2e

      - name: Calculate version
        id: calculateVersion
        run: |
          APP_VERSION=`cat package.json | jq ".version" -M | sed 's/\"//g'`
          echo "::set-output name=AppVersion::$APP_VERSION"
          echo "app version = v$APP_VERSION"
