name: "ci"

on:
  pull_request:
    branches:
      - cool
  push:
    branches:
      - cool

env:
  NODE_VERSION: "14.17.0"

jobs:
  ci_tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Audit check
        run: npm audit

      - name: Lint project
        run: npm run lint
