name: "ci"

on:
  pull_request:
    branches:
      - main

env: 
  MAIN_BRANCH: refs/heads/main

jobs:
  ci:
    uses: mrsauravsahu/actions/.github/workflows/ci-vscode-extension.yml@ci-vscode-extension/v0.3.0
